// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails binding surface. It delegates to the desktop runtime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AccountUsage reads session-limit windows for one sidebar page.
 */
export function AccountUsage(page: string): $CancellablePromise<desktop$0.AccountUsage[] | null> {
    return $Call.ByID(1844672859, page);
}

/**
 * Accounts lists browser logins for a sidebar page.
 */
export function Accounts(page: string): $CancellablePromise<desktop$0.Account[] | null> {
    return $Call.ByID(686820165, page);
}

/**
 * ApplyUpdate restarts into a downloaded release. It does not restart the proxy.
 */
export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(4175318290);
}

/**
 * CancelLogin stops the login that is waiting.
 */
export function CancelLogin(): $CancellablePromise<void> {
    return $Call.ByID(4242839088);
}

export function CheckUpdates(): $CancellablePromise<void> {
    return $Call.ByID(2263355335);
}

/**
 * DeleteAccount removes one browser-login file.
 */
export function DeleteAccount(id: string): $CancellablePromise<void> {
    return $Call.ByID(436436941, id);
}

/**
 * DownloadPendingUpdate downloads the release found by a find-only automatic
 * check, after the user picks 立即下载 in the new-release dialog.
 */
export function DownloadPendingUpdate(): $CancellablePromise<void> {
    return $Call.ByID(639904889);
}

/**
 * Home returns the setup state and client-facing connection details.
 */
export function Home(): $CancellablePromise<desktop$0.HomeSnapshot> {
    return $Call.ByID(630154502);
}

/**
 * HomeModels reads models from the running local proxy.
 */
export function HomeModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3195542688);
}

/**
 * KimiProviders returns the Kimi page.
 */
export function KimiProviders(): $CancellablePromise<desktop$0.OpenAIDraft[] | null> {
    return $Call.ByID(94605551);
}

/**
 * Login opens the system browser for one upstream.
 */
export function Login(provider: string): $CancellablePromise<void> {
    return $Call.ByID(1387155178, provider);
}

/**
 * ProviderKeys returns API keys for codex, grok, claude, or gemini.
 */
export function ProviderKeys(provider: string): $CancellablePromise<desktop$0.KeyDraft[] | null> {
    return $Call.ByID(1234357744, provider);
}

/**
 * Restart stops the service and starts the saved config.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(1363004932);
}

/**
 * SaveKimi writes the Kimi page.
 */
export function SaveKimi(drafts: desktop$0.OpenAIDraft[] | null): $CancellablePromise<void> {
    return $Call.ByID(1631049426, drafts);
}

/**
 * SaveProviderKeys writes one native provider's API keys.
 */
export function SaveProviderKeys(provider: string, drafts: desktop$0.KeyDraft[] | null): $CancellablePromise<void> {
    return $Call.ByID(1120453941, provider, drafts);
}

/**
 * SaveService writes the 服务 page.
 */
export function SaveService($in: desktop$0.ServiceSettings): $CancellablePromise<void> {
    return $Call.ByID(1089803907, $in);
}

/**
 * SaveUpdatePrefs applies the 关于 tab's update preferences immediately.
 */
export function SaveUpdatePrefs($in: desktop$0.AppPrefs): $CancellablePromise<$models.UpdatePrefsStatus> {
    return $Call.ByID(2750775117, $in);
}

/**
 * ServiceSettings returns the 服务 page.
 */
export function ServiceSettings(): $CancellablePromise<desktop$0.ServiceSettings> {
    return $Call.ByID(640618321);
}

/**
 * SetPresentation keeps the native menu and window background in sync with the renderer.
 */
export function SetPresentation(language: string, dark: boolean): $CancellablePromise<void> {
    return $Call.ByID(1410094571, language, dark);
}

/**
 * Start binds the saved config.
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1627660663);
}

/**
 * Status returns the navbar button and listen address.
 */
export function Status(): $CancellablePromise<desktop$0.Status> {
    return $Call.ByID(2836613335);
}

/**
 * Stop cancels the embedded service.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(4158193117);
}

/**
 * UpdatePrefStatus returns the 关于 tab's preferences and last check result.
 */
export function UpdatePrefStatus(): $CancellablePromise<$models.UpdatePrefsStatus> {
    return $Call.ByID(2284164635);
}

export function Version(): $CancellablePromise<string> {
    return $Call.ByID(2431199839);
}
