// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktop$0 from "./internal/desktop/models.js";

/**
 * UpdatePrefsStatus is what the 关于 tab shows for update preferences.
 */
export interface UpdatePrefsStatus {
    "prefs": desktop$0.AppPrefs;
    "lastCheckAt": string;
    "lastCheckResult": string;
    "latestVersion": string;
    "platform": string;
}
