// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Account is a browser-login record safe to show in the window.
 */
export interface Account {
    "id": string;
    "provider": string;
    "label": string;
    "needsReauthorization": boolean;
}

/**
 * AccountUsage is the session-limit reading for one saved login.
 */
export interface AccountUsage {
    "id": string;
    "plan": string;
    "windows": UsageWindow[] | null;
    "extra": UsageExtra | null;
    "resetCredits": number | null;
    "error": string;
}

/**
 * AppPrefs is the application-owned preference set. It lives in app.json and
 * never touches config.yaml, whose parser drops unknown fields.
 */
export interface AppPrefs {
    "autoUpdate": boolean;
    "autoCheck": boolean;
    "checkIntervalHours": number;
    "usageEnabled": boolean;
    "usagePercentMode": string;
    "usageResetMode": string;
    "usageShowExtra": boolean;
    "usageShowResets": boolean;
    "usageAlwaysShowPacing": boolean;
    "language": string;
    "theme": string;
    "livestream": boolean;
    "cliEnabled": boolean;
}

/**
 * CLIStatus is the command-line switch and the latest install failure.
 */
export interface CLIStatus {
    "enabled": boolean;
    "error": string;
}

/**
 * HomeSnapshot contains client-facing setup data, never upstream secrets.
 */
export interface HomeSnapshot {
    "hasCredentials": boolean;
    "clientKeys": string[] | null;
    "status": Status;
}

/**
 * KeyDraft is one upstream API key edited on a provider page.
 */
export interface KeyDraft {
    "apiKey": string;
    "baseUrl": string;
    "prefix": string;
}

/**
 * ModelDraft is one client-visible model on an OpenAI-compatible provider.
 */
export interface ModelDraft {
    "name": string;
    "alias": string;
}

/**
 * OpenAIDraft is one OpenAI-compatible upstream.
 */
export interface OpenAIDraft {
    "name": string;
    "baseUrl": string;
    "apiKeys": string[] | null;
    "models": ModelDraft[] | null;
}

/**
 * ServiceSettings is the 服务 page.
 */
export interface ServiceSettings {
    "listenMode": string;
    "customHost": string;
    "port": number;
    "clientApiKeys": string[] | null;
    "proxyUrl": string;
    "routingStrategy": string;
    "debug": boolean;
}

/**
 * Status is the navbar control and the address clients should use.
 */
export interface Status {
    "running": boolean;
    "action": string;
    "address": string;
    "allInterfaces": boolean;
    "restartRequired": boolean;
    "savedAddress": string;
    "error": string;
    "loginActive": boolean;
}

export interface UsageExtra {
    "amount": number;
    "currency": string;
    "kind": string;
}

/**
 * UsageWindow is one vendor rate-limit window. Used is the percent already consumed, 0–100.
 */
export interface UsageWindow {
    "kind": string;
    "used": number;
    "resetsAt": string;
    "durationSeconds": number;
}
