// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccountUsage(arg1) {
  return window['go']['main']['App']['AccountUsage'](arg1);
}

export function Accounts(arg1) {
  return window['go']['main']['App']['Accounts'](arg1);
}

export function CancelLogin() {
  return window['go']['main']['App']['CancelLogin']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function KimiProviders() {
  return window['go']['main']['App']['KimiProviders']();
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function OpenAIProviders() {
  return window['go']['main']['App']['OpenAIProviders']();
}

export function ProviderKeys(arg1) {
  return window['go']['main']['App']['ProviderKeys'](arg1);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SaveKimi(arg1) {
  return window['go']['main']['App']['SaveKimi'](arg1);
}

export function SaveOpenAI(arg1) {
  return window['go']['main']['App']['SaveOpenAI'](arg1);
}

export function SaveProviderKeys(arg1, arg2) {
  return window['go']['main']['App']['SaveProviderKeys'](arg1, arg2);
}

export function SaveService(arg1) {
  return window['go']['main']['App']['SaveService'](arg1);
}

export function ServiceSettings() {
  return window['go']['main']['App']['ServiceSettings']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
