// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function AccountUsage(arg1:string):Promise<Array<desktop.AccountUsage>>;

export function Accounts(arg1:string):Promise<Array<desktop.Account>>;

export function CancelLogin():Promise<void>;

export function DeleteAccount(arg1:string):Promise<void>;

export function KimiProviders():Promise<Array<desktop.OpenAIDraft>>;

export function Login(arg1:string):Promise<void>;

export function OpenAIProviders():Promise<Array<desktop.OpenAIDraft>>;

export function ProviderKeys(arg1:string):Promise<Array<desktop.KeyDraft>>;

export function Restart():Promise<void>;

export function SaveKimi(arg1:Array<desktop.OpenAIDraft>):Promise<void>;

export function SaveOpenAI(arg1:Array<desktop.OpenAIDraft>):Promise<void>;

export function SaveProviderKeys(arg1:string,arg2:Array<desktop.KeyDraft>):Promise<void>;

export function SaveService(arg1:desktop.ServiceSettings):Promise<void>;

export function ServiceSettings():Promise<desktop.ServiceSettings>;

export function Start():Promise<void>;

export function Status():Promise<desktop.Status>;

export function Stop():Promise<void>;
